### ISSUE TITLE
Deleted 0.4 runtime causes first time setup to fail

### ISSUE THREAD

**Issue by Meister1593** [bottlesdevs/runtime#1]
I use latest version of bottles from Flatpak and i can't complete first-time setup because release 0.4 was deleted.
This is what i get when running bottles and trying to wait for first time setup completion:
```
21:21:07 (INFO) Installing component: [runtime-0.4]. 
21:21:08 (WARNING) Failed to download [https://github.com/bottlesdevs/runtime/releases/download/0.4/runtime.tar.gz] with code: 404 != 200 
21:21:08 (ERROR) Extraction failed! Archive ends earlier than expected. 
21:21:09 (WARNING) No runtime found. 
```
Because of this, it's impossible to launch program completely.

**Comment by mirkobrombin** [comment]
Fixed
